version: "3"
services:
  keycloak:
    container_name: keycloak-user
    image: bitnami/keycloak:22.0.1
    volumes:
      - ./import:/opt/bitnami/keycloak/data/import
    environment:
      KEYCLOAK_DATABASE_HOST: keycloak_db
      KEYCLOAK_DATABASE_NAME: keycloakdb
      KEYCLOAK_DATABASE_USER: mikolajjanusz
      KEYCLOAK_DATABASE_PASSWORD: postgres
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password
      KEYCLOAK_HTTP_PORT: 9000
      KEYCLOAK_EXTRA_ARGS: "--import-realm"
    ports:
      - "9000:9000"
  keycloak_db:
    image: postgres
    container_name: keycloak_db_user
    restart: unless-stopped
    environment:
      POSTGRES_USER: mikolajjanusz
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: keycloakdb
    ports:
      - "5430:5432"
    healthcheck:
      test: "exit 0"